version: '3'

volumes:
  static_files:
  media_files:

services:
  web:
    build:
      context: .
      dockerfile: restaurantapp/pro/Dockerfile-production
    command: gunicorn -w 4 restaurantapp.wsgi -b 0.0.0.0:8000
    volumes:
      - static_files:/staticfiles
      - media_files:/mediafiles
      - ./restaurantapp:/restaurantapp
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=restaurantapp.production-settings
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=restaurantapp
      - POSTGRES_USER=restaurantapp 
      - POSTGRES_PASSWORD=restaurantapp  

  nginx:
      build:
        context: .
        dockerfile: restaurantapp/nginx/Dockerfile-nginx
      volumes:
        - static_files:/staticfiles
        - media_files:/mediafiles
      ports:
        - "8080:80"
      depends_on:
        - web